# StreakSync SwiftLint Configuration - Production Ready
# Place this file in your project root directory

# Paths to include/exclude
included:
  - StreakSync
  - StreakSyncShareExtension
  - StreakSyncTests

excluded:
  - Carthage
  - Pods
  - .build
  - DerivedData
  - .swiftpm

# Reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging)
reporter: "xcode"

# Rules Configuration
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - colon
  - comma
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - expiring_todo
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - function_default_parameter_at_end
  - ibinspectable_in_extension
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - missing_docs
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - no_space_in_method_call
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefixed_toplevel_constant
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - unused_declaration
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

disabled_rules:
  - todo # We'll handle TODOs manually
  - line_length # We'll set custom line length
  - type_body_length # We'll set custom type body length

# Custom Rules Configuration
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 400
  error: 500
  ignore_comment_only_lines: true

function_body_length:
  warning: 50
  error: 80

function_parameter_count:
  warning: 6
  error: 8

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 50
  excluded:
    - iPhone # Allow iPhone as type name
    - URL
    - ID

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - url
    - x
    - y
    - z

cyclomatic_complexity:
  warning: 10
  error: 15

nesting:
  type_level:
    warning: 2
    error: 3
  statement_level:
    warning: 5
    error: 7

# Force Unwrapping Configuration (CRITICAL)
force_unwrapping:
  severity: error # Make force unwrapping an ERROR

# Missing Docs Configuration
missing_docs:
  warning:
    - public
    - open
  error:
    - open

# File Header Configuration
file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*\.swift
                    \/\/  StreakSync.*
                    \/\/
                    \/\/  .*

# Trailing Whitespace
trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: false

# Custom message for specific rules
custom_rules:
  no_print_statements:
    name: "No Print Statements in Production"
    regex: '\bprint\s*\('
    message: "Use Logger instead of print statements"
    severity: warning
    
  no_force_try:
    name: "No Force Try"
    regex: '\btry!\s'
    message: "Use proper error handling instead of try!"
    severity: error
    
  no_force_cast:
    name: "No Force Cast"
    regex: '\bas!\s'
    message: "Use safe casting with 'as?' and proper error handling"
    severity: error

  proper_logging:
    name: "Use Logger Instead of Print"
    regex: 'print\s*\('
    message: "Use Logger from OSLog framework instead of print"
    severity: warning

  no_hardcoded_strings:
    name: "No Hardcoded Strings"
    regex: '(Text|Button|Label)\s*\(\s*"[^"]+"\s*\)'
    message: "Use NSLocalizedString for user-facing text"
    severity: warning

# Analyzer Rules
analyzer_rules:
  - unused_declaration
  - unused_import

# Additional Configuration
warning_threshold: 50
error_threshold: 100

# Compilation Database
compilation_database_path: compile_commands.json
